/**
 * Fabric client API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Result object of chaincode transaction request
 */
 export interface ChaincodeTransactionResult {
  /**
   * Function name in chaincode to be executed
   */
  func: string;
  /**
   * Result of request
   */
  result?: any;
  /**
   * Channel name where chaincode is deployed
   */
  channelName: string;
  /**
   * Chaincode name where chaincode is deployed
   */
  chaincodeName: string;
}
